import Providers from "@/app/providers"
import InitialPageLoader from "@/components/initial-page-loader"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import React, { FunctionComponent } from "react"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

type Props = Readonly<{
  children: React.ReactNode
}>

const RootLayout: FunctionComponent<Props> = ({ children }) => {
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning>
    <Providers>
      <InitialPageLoader/>
      <main className="flex flex-col h-screen w-screen bg-gradient-to-r from-[#EAEAEA] via-[#DBDBDB] to-[#F2F2F2]">
        {children}
      </main>
    </Providers>
    </body>
    </html>
  )
}

export default RootLayout
